<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ErWwpr\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ErWwpr/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container7ErWwpr.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container7ErWwpr\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container7ErWwpr\appAppKernelProdContainer([
    'container.build_hash' => '7ErWwpr',
    'container.build_id' => '2b6318f4',
    'container.build_time' => 1685633199,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7ErWwpr');
